Refactoring & Enhanced Code Readability
yunfachi/yunfaRemember pull request #2
Opened 2024-07-28 22:03 UTC by nulledphx

2024-07-28 22:06 UTC, nulledphx reviewed
👍📌

2024-07-29 04:58 UTC, BANanaD3V requested changes
Please change naming to something normal

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +import moe.yunfachi.yunfaremember.config.mewnjHHHHH;
Please change to something normal

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +import moe.yunfachi.yunfaremember.config.jfjfiSNdh;
Change to something normal too

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> -)
Fix formatting as it was before

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +    public YunfaRemember(@NotNull ProxyServer e, @NotNull Logger f, @DataDirectory Path g) {
We should change letters to actual names

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +    public void t     (@NotNull ServerPreConnectEvent u) {
This entire function contains letters and strange naming

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +    public void ee(@NotNull PlayerChooseInitialServerEvent ff) {
Strange naming

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> +            } else {jj(ff, null); /* devnull */}
Same here

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/YunfaRemember.java
> -    public void log(@NotNull Level level, @NotNull String message, @NotNull Throwable... exceptions) {
Please, change it

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/config/mewnjHHHHH.java
> +public class mewnjHHHHH {
Bad naming everywhere in file

2024-07-29 04:58 UTC, BANanaD3V commented on src/main/java/moe/yunfachi/yunfaremember/config/jfjfiSNdh.java
> +public class jfjfiSNdh {
Bad naming in file

2024-08-01 13:13 UTC, closed without merging